services:
  ia-service:
    build: ./backend/ia-service
    container_name: ia_service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    ports:
      - "8001:8000"
    depends_on:
      pgvector:
        condition: service_healthy
    volumes:
      - ./docs:/app/docs
      - ./backend/ia-service/ia_service:/app/ia_service
    environment:
      - POSTGRES_HOST=pgvector
      - DOCS_DIR=/app/docs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped

  java-backend:
    build: ./backend/nlp4re
    container_name: java_backend
    env_file:
      - ./.env
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: unless-stopped

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    env_file:
      - ./.env
    ports:
      - "5435:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  db:
    image: postgres:16-alpine
    container_name: db_users
    env_file:
      - ./.env
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgvector_data:
  postgres_data:
