services:
  ia-service:
    container_name: ia-service
    build: ./backend/ia-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    ports:
      - "${RAG_SERVICE_PORT}:8000"
    depends_on:
      rag-db:
        condition: service_healthy
    volumes:
      - ./docs:/app/docs
      - ./backend/ia-service/ia_service:/app/ia_service
    environment:
      POSTGRES_HOST: rag-db
      DOCS_DIR: /app/docs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: no

  users-service:
    container_name: users-service
    build: ./backend/nlp4re
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${USER_SERVICE_PORT}:8080"
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${DB_USERS_PORT}
      POSTGRES_DB: ${DB_USERS}
      POSTGRES_USER: ${DB_USERS_USER}
      POSTGRES_PASSWORD: ${DB_USERS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    restart: no

  rag-db:
    container_name: rag-db
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${DB_RAG_USER}
      POSTGRES_PORT: ${DB_RAG_PORT}
      POSTGRES_PASSWORD: ${DB_RAG_PASSWORD}
      POSTGRES_DB: ${DB_RAG}

    ports:
      - "${DB_RAG_PORT}:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: no
  
  users-db:
    container_name: users-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERS_USER}
      POSTGRES_PORT: ${DB_USERS_PORT}
      POSTGRES_PASSWORD: ${DB_USERS_PASSWORD}
      POSTGRES_DB: ${DB_USERS}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "${DB_USERS_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: no

volumes:
  pgvector_data:
  postgres_data:
